### ISSUE TITLE
Consider Removing "Uses"

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-text-import#23]
The `Uses` statement is much like an `import` in other languages -- it is intended to identify namespaces to search when resolving references to element names.

In theory it is a good idea, but in practice, it's proven to be annoying -- and does not seem to add much value since naming clashes are extremely rare in SHR.

We should consider removing `Uses` and always search for elements globally (whatever namespace they may be in).  This will be more user friendly and shouldn't introduce too many problems (we think).  When there are naming collisions, a reference to an element can always use a fully qualified name (e.g., `shr.core.Address`).

**Comment by markkramerus** [comment]
Moving this suggestion to the modularity discussion. If there are explicit dependencies in one file, then Uses could be eliminated.
