### ISSUE TITLE
Support for libraries

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-text-import#24]
When creating non-SHR IGs, its very helpful to still use some SHR definitions (especially core ones like CodeableConcept, Quantity, but also ones like Observation -- so that the FHIR mappings can be re-used).

Currently, if an IG wants these, it needs to include their text definitions with its own files.  This has three main drawbacks:

1. They might unintentionally (or perhaps intentionally) modify definitions of core SHR elements -- which can be confusing.
2. With the new config feature, the SHR elements get de-branded and take on the brand of the IG (including the base URL in the URL identifiers).  This results in things like _Acme CodeableConcept_.
3. The SHR elements get republished in their IG and perhaps detract from the focus of the IG.

We should consider first how the SHR definitions can be re-used, but remain in tact with their own branding -- and not be republished in a custom IG.  This might be done through a library concept.

Once the library concept is in place, perhaps it could be used to bring in other IGs too (not just SHR).

**Comment by markkramerus** [comment]
This is already part of the modularity discussion.  https://github.com/standardhealth/shr_spec/wiki/Modularity-and-Packaging
