### ISSUE TITLE
Need Better Standard Model / Serialization

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-text-import#25]
Currently, CAMEO is parsed into ES6 classes from _shr-models_.  While this works in the middle of a process chain, it would be beneficial to have a standard model that is serializable, can be persisted, or passed around more easily.  The JSON from _shr-json_ is a start, but suffers from several issues, namely that it was designed to control website generation (so has that flavor) and is expressed in a single file (which is getting too large).

**Comment by markkramerus** [comment]
OBE.
