### ISSUE TITLE
Resolve namespaces in paths independently of 'uses'

### ISSUE THREAD

**Issue by Abhijay** [standardhealth/shr-text-import#34]
In the test fixture: 
```
Grammar:    DataElement 5.1
Namespace:  shr.test
Uses:       shr.core // This shouldn't be needed, but due to bug in importer, it is!

CodeSystem:     FOO = http://foo.org

EntryElement:   SpecialParent
Value:          0..1 string

EntryElement:   SpecialChild
Based on:        SpecialParent
1..1 _Value
0..0 _Entry.Version
```

Without an import on `shr.core`, the following error is raised due to an inability to resolve the namespace of `SpecialChild`'s `_Entry.Version`:
```      
AssertionError: Import Errors: Failed to resolve definition for Version. ERROR_CODE:11013: expected 1 to equal 0
```

The `shr.core` import should not be necessarily, as `SpecialChild`'s `_Entry.Version` should be able to resolve the namespace from the parent element's (`_Entry`) dependencies.

**Comment by markkramerus** [comment]
OBE. No _x type keywords in Grammar 6.x
